enh: Support evaluation of different software versions, evaluate-overlap helper and -id col

diff --git a/bin/submit-condor-jobs b/bin/submit-condor-jobs
--- a/bin/submit-condor-jobs
+++ b/bin/submit-condor-jobs
@@ -7,27 +7,34 @@
 ## workflow. It has to be run multiple times until all steps
 ## are done, as indicated by the last message to STDOUT.
 
+nosubmit=false
+
 print_help()
 {
-  error "usage: $(basename $BASH_SOURCE) <dataset> <regid> [<cfgid>...]"
+  error "usage: $(basename $BASH_SOURCE) -d <dataset> -r <regid> [-nosubmit] [--] [<cfgids>]"
 }
 
 submit()
 {
-  local i=0
-  local n=3
-  local s=30
-  echo "> condor_submit $@"
-  while [ $i -lt $n ]; do
-    condor_submit "$@" && break
-    let i++
-    if [ $i -eq $n ]; then
-      error "Job submission failed for $n times, aborting"
-    fi
-    echo "Job submission failed, trying again in $s sec..."
-    sleep $s
-  done
-  jobs_submitted=true
+  grep -e '^ *queue' "$1" > /dev/null
+  if [ $? -eq 0 ]; then
+    local i=0
+    local n=3
+    local s=30
+    echo "> condor_submit $1"
+    while [ $i -lt $n ]; do
+      [ $nosubmit = true ] || condor_submit "$1" && break
+      let i++
+      if [ $i -eq $n ]; then
+        error "Job submission failed for $n times, aborting"
+      fi
+      echo "Job submission failed, trying again in $s sec..."
+      sleep $s
+    done
+    jobs_submitted=true
+  else
+    error "No jobs in $1, but could not find output files before?!"
+  fi
 }
 
 # ------------------------------------------------------------------------------
@@ -44,8 +51,33 @@ submit()
 # change to top-level directory
 run cd "$topdir"
 
+cfgids=()
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -d|-dataset)
+      dataset="$2"
+      shift; ;;
+    -r|-reg|regid)
+      regid="$2"
+      shift; ;;
+    -nosubmit)
+      nosubmit=true
+      ;;
+    -*)
+      error "Unknown option: $1"
+      ;;
+    --)
+      shift
+      cfgids=("${cfgids[@]}" "$@")
+      break; ;;
+    *)
+      cfgids=("${cfgids[@]}" "$1")
+      ;;
+  esac
+  shift
+done
+
 # evaluation dataset
-dataset="$1"; shift
 [ -n "$dataset" ] || print_help
 . "$setdir/$dataset.sh" || exit 1
 [ ${#chns[@]}   -eq 1 ] || error "$setdir/$dataset.sh: chns must be array of length 1"
@@ -55,13 +87,14 @@ dataset="$1"; shift
 let N="${#tgtids[@]} * ${#srcids[@]}"
 
 # registration method
-regid="$1"; shift
 [ -n "$regid" ] || print_help
+version="${regid/*-}"
+[ $(is_version "$version") = true ] || version=''
 
 # generate parameters CSV or check existence of it or preset .cfg file
 regcfg_found=false
 for cfgpre in "$dataset/" ''; do
-  if [ -f "$cfgdir/$cfgpre$regid.csv" ] || [ -f "$cfgdir/$cfgpre$regid.cfg" ]; then
+  if [ -f "$cfgdir/$cfgpre$regid.csv" -o -f "$cfgdir/$cfgpre$regid.cfg" ]; then
     regcfg_found=true
     break
   fi
@@ -70,13 +103,24 @@ for cfgpre in "$dataset/" ''; do
     regcfg_found=true
     break
   fi
+  if [ -n "$version" ]; then
+    _regid=${regid%-*}
+    if [ -f "$cfgdir/$cfgpre${_regid}.csv" -o -f "$cfgdir/$cfgpre${_regid}.cfg" ]; then
+      regcfg_found=true
+      break
+    fi
+    if [ -f "$cfgdir/$cfgpre${_regid}.gen" ]; then
+      run "$cfgdir/$cfgpre${_regid}.gen"
+      regcfg_found=true
+      break
+    fi
+  fi
 done
 if [ $regcfg_found = false ]; then
   error "Require either one of '$cfgdir/[$dataset/]$regid.{csv,cfg,gen}'"
 fi
 
 # IDs of parameter sets
-cfgids=("$@")
 [ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$dataset" "$regid"))
 [ ${#cfgids} -gt 0 ] || error "etc/settings.sh: get_cfgids is empty for $regid"
 issym="$(is_sym $regid)"
@@ -90,14 +134,14 @@ imgsuf=".nii.gz"
 # ------------------------------------------------------------------------------
 # disable evaluation measures that cannot be computed
 if [ $evlice = true ]; then
-  if [ ${#tgtids[@]} -ne ${#srcids} ]; then
+  if [ ${#tgtids[@]} -ne ${#srcids[@]} ]; then
     echo "Info: Skipping evaluation of inverse consistency error because not all srcimgs are used as tgtimgs."
   elif [ $issym = true -a $allsym != true ]; then
     echo "Info: Skipping evaluation of inverse consistency error because allsym not 'true'."
   fi
   evlice=false
 fi
-if [ $evlmte = true -a ${#tgtids[@]} -ne ${#srcids} ]; then
+if [ $evlmte = true -a ${#tgtids[@]} -ne ${#srcids[@]} ]; then
   echo "Info: Skipping evaluation of mean transitivity error because not all srcimgs are used as tgtimgs."
   evlmte=false
 fi
diff --git a/lib/condor/gen-register-niftyreg b/lib/condor/gen-register-niftyreg
--- a/lib/condor/gen-register-niftyreg
+++ b/lib/condor/gen-register-niftyreg
@@ -33,7 +33,9 @@ dataset="$1"; shift
 regid="$1"; shift
 [ -n "$regid" ] || print_help
 issym="$(is_sym $regid)"
-regcmd=${regid/*-}
+
+version="${regid/*-}"
+[ $(is_version "$version") = true ] || version=''
 
 # images that drive the registration
 chn="${chns[0]}"
@@ -72,8 +74,12 @@ if [ -f "$cfgdir/$dataset/$regid.csv" ]; then
   regcsv="$cfgdir/$dataset/$regid.csv"
 elif [ -f "$cfgdir/$regid.csv" ]; then
   regcsv="$cfgdir/$regid.csv"
+elif [ -n "$version" -a -f "$cfgdir/$dataset/${regid%-*}.csv" ]; then
+  regcsv="$cfgdir/$dataset/${regid%-*}.csv"
+elif [ -n "$version" -a -f "$cfgdir/${regid%-*}.csv" ]; then
+  regcsv="$cfgdir/${regid%-*}.csv"
 else
-  error "Missing $regid.csv parameters file in $cfgdir[/$dataset]"
+  error "Missing parameters CSV file for $regid (version='$version') in $cfgdir[/$dataset]"
 fi
 paropt=($(head -n1 "$regcsv" | tr , '\n'))
 
@@ -86,7 +92,7 @@ for cfgid in "${cfgids[@]}"; do
 
   # paths
   jobdir="$regdir/$cfgid/bin"
-  cppdir="$regdir/$cfgid/dof"
+  dofdir="$regdir/$cfgid/dof"
   logdir="$regdir/$cfgid/log/register"
   pardir="$regdir/$cfgid/etc"
 
@@ -105,7 +111,7 @@ for cfgid in "${cfgids[@]}"; do
   # construct list of reg_f3d arguments
   c=0
   argv=()
-  [ -z "$bgvalue" ] || argv=('-pad' "$bgvalue")
+  [ -z "$bgvalue" ] || argv=("${argv[@]}" '-pad' "$bgvalue")
   while [ $c -lt ${#paropt[@]} ]; do
     opt="${paropt[c]}"
     arg="${parval[c]}"
@@ -126,10 +132,10 @@ for cfgid in "${cfgids[@]}"; do
         ;;
       le)
         vals=($arg)
-        if [ ${#vals[@]} -ne 2 ]; then
+        if [ "$version" = "1.3.9" -a ${#vals[@]} -ne 2 ]; then
           error "Invalid 'le' value: $arg! Must be two numbers separated by space."
         fi
-        argv=("${argv[@]}" '-le' ${vals[0]} ${vals[1]})
+        argv=("${argv[@]}" '-le' ${vals[@]})
         ;;
       ds)
         argv=("${argv[@]}" '-sx' $arg '-sy' $arg '-sz' $arg)
@@ -140,9 +146,10 @@ for cfgid in "${cfgids[@]}"; do
     esac
     let c++
   done
+  [ -z "$version" ] || argv=("${argv[@]}" '-ver' "$version")
 
   # make directories
-  makedir "$cppdir"
+  makedir "$dofdir"
   makedir "$logdir"
   makedir "$jobdir"
 
@@ -161,8 +168,9 @@ initialdir   = $topdir
 EOF_HEADER
     for tgtid in "${tgtids[@]}"; do
     for srcid in "${srcids[@]}"; do
-      cppout="$cppdir/$tgtid-$srcid.nii.gz"
-      [ $force = true ] || [ ! -f "$cppout" ] || continue
+      dofout="$dofdir/$tgtid-$srcid.dof.gz"
+      cppout="$dofdir/$tgtid-$srcid.nii.gz"  # to allow check of conversion
+      [ $force = true ] || [ ! -f "$dofout" ] || continue
       [ $allsym = true ] || [ $issym != true ] || [[ $tgtid < $srcid ]] || [ $tgtid = $srcid ] || continue
       masks=()
       if [ -n "$mskdir" ]; then
@@ -172,7 +180,7 @@ EOF_HEADER
         fi
       fi
       cat >> "$jobdsc" <<EOF_QUEUE
-arguments = "-ref '$imgdir/$imgpre$tgtid$imgsuf' -flo '$imgdir/$imgpre$srcid$imgsuf' -cpp '$cppout' ${masks[@]} ${argv[@]}"
+arguments = "-ref '$imgdir/$imgpre$tgtid$imgsuf' -flo '$imgdir/$imgpre$srcid$imgsuf' -cpp '$cppout' -dof '$dofout' ${masks[@]} ${argv[@]}"
 error     = $logdir/$tgtid-$srcid.err
 output    = $logdir/$tgtid-$srcid.out
 log       = $logdir/$tgtid-$srcid.log
diff --git a/lib/tools/run-niftyreg-f3d b/lib/tools/run-niftyreg-f3d
--- a/lib/tools/run-niftyreg-f3d
+++ b/lib/tools/run-niftyreg-f3d
@@ -10,30 +10,56 @@
 [ ${mirtk:0:1} = / ] || mirtk="$topdir/$mirtk"
 [ ${niftyreg:0:1} = / ] || niftyreg="$topdir/$niftyreg"
 
-i=0
-args=("$@")
-while [ $i -lt $# ]; do
-  if [ "${args[i]}" = '-cpp' ]; then
-    let i++
-    cpp="${args[i]}"
-    break
-  fi
-  let i++
+args=()
+cpp=
+dof=
+res=
+version=
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -ver)
+      version="$2"
+      shift; ;;
+    -dof)
+      dof="$2"
+      shift; ;;
+    -cpp)
+      cpp="$2"
+      shift; ;;
+    -res)
+      res="$2"
+      shift; ;;
+    *)
+      args=("${args[@]}" "$1")
+      ;;
+  esac
+  shift
 done
 
-[ -n "$cpp" ] || error "Could not determine -cpp output file path"
-dof="${cpp/.nii/.dof}"
-[ "$dof" != "$cpp" ] || error "-cpp file name must have extension .nii or .nii.gz"
-[ "${dof:${#dof}-3}" = '.gz' ] || dof="$dof.gz"
-tmpdir="$(mktemp -d)"  # need specific file name extension, but --suffix option not available on macOS
-[ $? -eq 0 -a -n "$tmpdir" ] || error "Failed to create temporary directory for -res output file"
-res="$tmpdir/res.nii.gz"
+if [ -z "$cpp" -a -z "$dof" ]; then
+  error "Missing -cpp or -dof option argument"
+fi
+
+if [ -n "$version" ]; then
+  niftyreg="$niftyreg-$version"
+  [ -f "$niftyreg/bin/reg_f3d" ] || error "NiftyReg version $version not found in '$niftyreg'"
+fi
+
+if [ -z "$res" -o -z "$cpp" ]; then
+  tmp="$(mktemp -d)"
+  [ $? -eq 0 -a -n "$tmp" ] || error "Failed to create temporary directory"
+  [ -z "$res" ] || res="$tmp/res.nii.gz"
+  [ -z "$cpp" ] || cpp="$tmp/cpp.nii.gz"
+else
+  tmp=
+fi
 
 run()
 {
   echo "> $@"
   "$@" || {
-    [ -n "$tmpdir" -a "$tmpdir" != '/' ] || rm -rf "$tmpdir"
+    [ -z "$tmp" -o "$tmp" = / ] || rm -rf "$tmp"
     exit 1
   }
 }
@@ -41,5 +67,5 @@ run()
 echo "Host: $(hostname)"
 export LD_LIBRARY_PATH="$niftyreg/lib:$LD_LIBRARY_PATH"
 export DYLD_LIBRARY_PATH="$niftyreg/lib:$DYLD_LIBRARY_PATH"
-time run "$niftyreg/bin/reg_f3d" "$@" -res "$res"
-run "$mirtk" convert-dof "$cpp" "$dof" -input-format f3d
+time run "$niftyreg/bin/reg_f3d" "${args[@]}" -cpp "$cpp" -res "$res"
+[ -z "$dof" ] || run "$mirtk" convert-dof "$cpp" "$dof" -input-format f3d
