enh: Support dataset specific registration parameters

diff --git a/lib/condor/gen-register-elastix b/lib/condor/gen-register-elastix
--- a/lib/condor/gen-register-elastix
+++ b/lib/condor/gen-register-elastix
@@ -39,7 +39,7 @@ issym="$(is_sym $regid)"
 
 # IDs of parameter sets
 cfgids=("$@")
-[ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$regid"))
+[ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$dataset" "$regid"))
 [ ${#cfgids} -gt 0 ] || error "etc/settings.sh: get_cfgids is empty for $regid"
 
 # affinely pre-aligned images
@@ -58,11 +58,22 @@ if [ -n "$bgvalue" ]; then
   done
 fi
 
-# generate job description for each configuration
-regcsv="$cfgdir/$regid.csv"
-regdir="$vardir/$dataset/$regid"
+# dataset and registration specific parameters
+if [ -f "$cfgdir/$dataset/$regid.csv" ]; then
+  regcsv="$cfgdir/$dataset/$regid.csv"
+  config="$(cat "$cfgdir/$dataset/$regid.txt")"
+  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$dataset/$regid.txt"
+elif [ -f "$cfgdir/$regid.csv" ]; then
+  regcsv="$cfgdir/$regid.csv"
+  config="$(cat "$cfgdir/$regid.txt")"
+  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$regid.txt"
+else
+  error "Missing $regid.csv parameters file in $cfgdir[/$dataset]"
+fi
 paropt=($(head -n1 "$regcsv" | tr , '\n'))
-config="$(cat "$cfgdir/$regid.txt")"
+
+# generate job description for each configuration
+regdir="$vardir/$dataset/$regid"
 
 for cfgid in "${cfgids[@]}"; do
   jobdir="$regdir/$cfgid/bin"
diff --git a/lib/condor/gen-register-mirtk b/lib/condor/gen-register-mirtk
--- a/lib/condor/gen-register-mirtk
+++ b/lib/condor/gen-register-mirtk
@@ -36,20 +36,30 @@ isic="$(is_ic $regid)"
 
 # IDs of parameter sets
 cfgids=("$@")
-[ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$regid"))
+[ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$dataset" "$regid"))
 [ ${#cfgids} -gt 0 ] || error "etc/settings.sh: get_cfgids is empty for $regid"
 
-# generate job description for each configuration
-imgdir="$vardir/$dataset/affine/out"
-regdir="$vardir/$dataset/$regid"
-regcsv="$cfgdir/$regid.csv"
+# dataset and registration specific parameters
+if [ -f "$cfgdir/$dataset/$regid.csv" ]; then
+  regcsv="$cfgdir/$dataset/$regid.csv"
+  config="$(cat "$cfgdir/$dataset/$regid.txt")"
+  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$dataset/$regid.txt"
+elif [ -f "$cfgdir/$regid.csv" ]; then
+  regcsv="$cfgdir/$regid.csv"
+  config="$(cat "$cfgdir/$regid.txt")"
+  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$regid.txt"
+else
+  error "Missing $regid.csv parameters file in $cfgdir[/$dataset]"
+fi
 paropt=($(head -n1 "$regcsv" | tr , '\n'))
-config="$(cat "$cfgdir/$regid.txt")"
-dofin='Id'
-
 
 #                   Energy function =
 energy_indentation="                "
+
+# generate job description for each configuration
+regdir="$vardir/$dataset/$regid"
+imgdir="$vardir/$dataset/affine/out"
+dofin='Id'
 
 for cfgid in "${cfgids[@]}"; do
 
